-- ─── Migración de productos al catálogo (por encargo) ────────────────────────
-- Correr en: Supabase → SQL Editor → New query
-- ON CONFLICT DO NOTHING = no sobreescribe si ya existe el producto

INSERT INTO productos_catalogo (id, nombre, precio, categoria, tipo, talle, descripcion, imagen, imagen_espalda, stock)
VALUES
('1',  'Escocia Alternativa',        70000, 'alternativa', 'nacion', ARRAY['S','M','L','XL','2XL','3XL'], 'Camiseta alternativa de Escocia con diseño oscuro y el cardo nacional bordado en el pecho.',                           '/Escocia_alt_frente.png',          '/Escocia_alt_espalda.png',          15),
('3',  'FijianDrua Training',         70000, 'training',    'club',   ARRAY['S','M','L','XL','2XL'],       'Camiseta de training de los Fijian Drua, liviana y transpirable para el máximo rendimiento en cancha.',              '/FijianDrua_training_frente.png',   '/FijianDrua_training_espalda.png',  22),
('4',  'FijianDrua Training Alternativa', 70000, 'training', 'club',  ARRAY['S','M','L','XL'],             'Versión alternativa de la camiseta de training de los Fijian Drua, con diseño especial para entrenamientos.',       '/FijianDrua_training_alt_frente.png','/FijianDrua_training_alt_espalda.png', 12),
('5',  'Francia Alternativa',         70000, 'alternativa', 'nacion', ARRAY['S','M','L','XL'],             'Camiseta alternativa de Francia con el elegante diseño tricolor de la federación francesa.',                        '/Francia_alt_frente.png',           '/francia_alt_espalda.png',          18),
('6',  'Francia Local',               70000, 'local',       'nacion', ARRAY['S','M','L','XL','2XL','3XL'], 'Camiseta local del XV de France, el azul profundo que marca cada conquista del seleccionado galo.',                 '/Francia_frente.png',               '/francia_espalda.png',               9),
('7',  'Gales Alternativa',           70000, 'alternativa', 'nacion', ARRAY['S','M','L','XL'],             'Camiseta alternativa de Gales con diseño moderno que mantiene los colores del dragón galés.',                      '/Gales_alt_frente.png',             '/Gales_alt_espalda.png',            20),
('8',  'Gales Local',                 70000, 'local',       'nacion', ARRAY['S','M','L','XL','2XL'],       'Camiseta local del seleccionado galés, el rojo pasión que identifica a los hombres del dragón.',                   '/Gales_frente.png',                 '/Gales_espalda.png',                14),
('9',  'Harlequins Local',            70000, 'local',       'club',   ARRAY['S','M','L','XL'],             'Camiseta local de los Harlequins con el icónico diseño de cuartos multicolores del club londinense.',              '/Harlequins_frente.png',            '/Harlequins_espalda.png',           25),
('10', 'Inglaterra Local',            70000, 'local',       'nacion', ARRAY['S','M','L','XL','2XL','3XL'], 'Camiseta local de Inglaterra, el blanco clásico con la rosa roja de la Rugby Football Union.',                     '/Inglaterra_frente.png',            '/Inglaterra_espalda.png',           11),
('11', 'Irlanda Alternativa',         70000, 'alternativa', 'nacion', ARRAY['S','M','L','XL'],             'Camiseta alternativa del seleccionado irlandés con diseño moderno y el trébol de la IRFU.',                       '/Irlanda_alt_frente.png',           '/Irlanda_alt_espalda.png',          17),
('12', 'Irlanda Local',               70000, 'local',       'nacion', ARRAY['S','M','L','XL','2XL','3XL'], 'Camiseta local de Irlanda, el verde que une a las cuatro provincias bajo el trébol de la IRFU.',                  '/Irlanda_frente.png',               '/Irlanda_espalda.png',               8),
('13', 'Leinster Local',              70000, 'local',       'club',   ARRAY['S','M','L','XL'],             'Camiseta local del Leinster, el azul que domina el rugby europeo con múltiples Champions Cups.',                   '/Leinster_frente.png',              '/Leinster_espalda.png',             13),
('14', 'Lions Azul Alternativa',      70000, 'alternativa', 'club',   ARRAY['S','M','L','XL','2XL'],       'Camiseta alternativa azul de los British & Irish Lions, edición especial con diseño de gira.',                    '/Lions_alt_azul_frente.png',        '/lions_alt_azul_espalda.png',       19),
('15', 'Lions Verde Alternativa',     70000, 'alternativa', 'club',   ARRAY['S','M','L','XL','2XL'],       'Camiseta alternativa verde de los British & Irish Lions, edición exclusiva de gira por el Pacífico.',              '/Lions_alt_verde_frente.png',       '/lions_alt_verde_espalda.png',      24),
('16', 'Lions Local',                 70000, 'local',       'club',   ARRAY['S','M','L','XL'],             'Camiseta local de los British & Irish Lions, el rojo que une a Inglaterra, Irlanda, Escocia y Gales.',            '/Lions_frente.png',                 '/Lions_espalda.png',                16),
('17', 'Sudáfrica Chomba Local',      70000, 'local',       'nacion', ARRAY['S','M','L','XL'],             'Chomba oficial de los Springboks, el verde y dorado de los campeones del mundo en corte polo.',                   '/Sudafrica_chomba_frente.png',      '/Sudafrica_chomba_espalda.png',     21),
('18', 'Toulouse Local',              70000, 'local',       'club',   ARRAY['S','M','L','XL','2XL'],       'Camiseta local del Stade Toulousain, el club más ganador de la historia del rugby europeo.',                      '/Toulouse_frente.png',              '/Toulouse_espalda.png',             23),
('19', 'Wallabies Local',             70000, 'local',       'nacion', ARRAY['S','M','L','XL'],             'Camiseta local de los Wallabies, el amarillo dorado de Australia con el canguro del rugby nacional.',             '/Wallabies_frente.png',             '/wallabies_espalda.png',            10),
('20', 'Wallabies Training',          70000, 'training',    'nacion', ARRAY['S','M','L','XL','2XL'],       'Camiseta de training de los Wallabies, diseñada para la alta performance del seleccionado australiano.',           '/Wallabies_training_frente.png',    '/Wallabies_training_espalda.png',   14)
ON CONFLICT (id) DO NOTHING;
